### ISSUE TITLE
Showtimes does not work for german cinemas when the film is OmU (original with subtitles)

### ISSUE THREAD

**Issue by pumana** [spenap/butaca#34]
When you click on a movie in the showtime list for film theaters in Germany with a film in original tone (OmU in german - "Original mit Untertitel" or original with subtitles in english) the movie info box is empty (no result found). The app must simple cut off the characters "(OmU)" after the movie title so the movie info can be fetched correctly from the server without need to correct the title manually every time.

**Comment by mporsch** [comment]
Thanks for the bug report! I am able to confirm the issue. But I'll rather leave it as it is for 3 reasons:
* in my current list I see one movie with "(OV)" instead of ("OmU"); other cinemas and other languages will have their own weird abbrevations. So fixing this would require a growing list of regex's for cutting these off. With the possibility of false positives, I think in the end this may cause more issues than  what it's worth.
* the search text box correctly displays the search string. So it should be obvious for most users that the appended "(OmU)" causes the trouble.
* actually, I think that the search engine (https://www.themoviedb.org in this case) should be robust to such issues and it is not up to the individual apps to fix it.
